WebAppKuspyKreme/Models/Coupon.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace WebAppKuspyKreme.Models
{
    public class Coupon
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Duration required")]
        [Display(Prompt ="YYYY/MM/DD")]
        public string Duration { get; set; }

        public Status Status { get; set; }
        public Establishment Establishment { get; set; }

        //[ReadOnly(true)]
        [Required(ErrorMessage = "Serie required")]
        public string Serie { get; set; }

        [Required(ErrorMessage = "Description required")]
        public string Description { get; set; }
        public string CreatedAt { get; set; }
        public string UpdatedAt { get; set; }
        public string DeletedAt { get; set; }
    }
}

WebAppKuspyKreme/Controllers/CouponController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebAppKuspyKreme.Models;
using X.PagedList;
using OfficeOpenXml;
using System.Threading.Tasks;
//using OfficeOpenXml.Core.ExcelPackage;

namespace WebAppKuspyKreme.Controllers
{
    public class CouponController : Controller
    {
        private HttpClient httpClient;
        public string urlBase;

        public CouponController()
        {
            httpClient = new HttpClient();
            urlBase = "http://localhost:60861/Service.svc/";
        }

        // GET: Coupon
        public async Task<ActionResult> Index(int? page = 1)
        {
            try
            {
                var responseApi = await httpClient.GetAsync($"{urlBase}/coupons");
                if (responseApi.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    string response = await responseApi.Content.ReadAsStringAsync();
                    var parseResponse = JsonConvert.DeserializeObject<ResponseBase<Coupon>>(response);

                    if (parseResponse.Success && parseResponse.List != null)
                    {
                        int pageNumber = (page ?? 1);
                        var onePageOfStudents = parseResponse.List.ToPagedList(pageNumber, 12);
                        ViewBag.PageList = onePageOfStudents;
                        return View(onePageOfStudents);
                    }
                    else
                    {
                        ViewBag.Error = parseResponse.Messaje;
                        return View("Error");
                    }
                }

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.ToString();
                return View("Error");
            }

            return View();

        }

        // GET: Coupon/Details/5
        public async Task<ActionResult> Details(int id)
        {
            try
            {
                var responseApi = await httpClient.GetAsync($"{urlBase}/coupons/{id}");
                if (responseApi.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    string response = await responseApi.Content.ReadAsStringAsync();
                    var parseResponse = JsonConvert.DeserializeObject<ResponseBase<Coupon>>(response);

                    if (parseResponse.Success && parseResponse.Element != null)
                    {
                        return View(parseResponse.Element);
                    }
                    else
                    {
                        ViewBag.Error = parseResponse.Messaje;
                        return View("Error");
                    }
                }

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.ToString();
                return View("Error");
            }

            return View();
        }

        // GET: Coupon/Create
        public ActionResult Create()
        {
            ViewBag.ListEstablishment = Utils.Util.GetEstablishments().ConvertAll(d =>
            {
                return new SelectListItem
                {
                    Text = d.Name,
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.ListStatus = Utils.Util.GetEstatus().ConvertAll(d =>
            {
                return new SelectListItem
                {
                    Text = d.Name,
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            Coupon coupon = new Coupon()
            {
                Serie = Utils.Util.GenerateGuid(7)
            };

            return View(coupon);
        }

        // POST: Coupon/Create
        [HttpPost]
        public async Task<ActionResult> Create(Coupon coupon)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var content = new StringContent(JsonConvert.SerializeObject(coupon), Encoding.UTF8, "application/json");
                    var responseApi = await httpClient.PostAsync($"{urlBase}/coupons", content);

                    if (responseApi.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        string response = await responseApi.Content.ReadAsStringAsync();
                        var parseResponse = JsonConvert.DeserializeObject<ResponseBase<Coupon>>(response);

                        if (parseResponse.Success)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ViewBag.Error = parseResponse.Messaje;
                            return View("Error");
                        }
                    }
                }
                catch (Exception ex)
                {
                    ViewBag.Error = ex.ToString();
                    return View("Error");
                }
            }

            return View();
        }

        // GET: Coupon/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            ViewBag.ListEstablishment = Utils.Util.GetEstablishments().ConvertAll(d =>
            {
                return new SelectListItem
                {
                    Text = d.Name,
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.ListStatus = Utils.Util.GetEstatus().ConvertAll(d =>
            {
                return new SelectListItem
                {
                    Text = d.Name,
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            try
            {
                var responseApi = await httpClient.GetAsync($"{urlBase}/coupons/{id}");
                if (responseApi.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    string response = await responseApi.Content.ReadAsStringAsync();
                    var parseResponse = JsonConvert.DeserializeObject<ResponseBase<Coupon>>(response);

                    if (parseResponse.Success && parseResponse.Element != null)
                    {
                        return View(parseResponse.Element);
                    }
                    else
                    {
                        ViewBag.Error = parseResponse.Messaje;
                        return View("Error");
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.ToString();
                return View("Error");
            }

            return View();
        }

        // POST: Coupon/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Coupon coupon)
        {
            try
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(coupon), Encoding.UTF8, "application/json");
                var responseApi = await httpClient.PutAsync($"{urlBase}/coupons/{id}", content);

                if (responseApi.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    string response = await responseApi.Content.ReadAsStringAsync();
                    var parseResponse = JsonConvert.DeserializeObject<ResponseBase<Coupon>>(response);

                    if (parseResponse.Success)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Error = parseResponse.Messaje;
                        return View("Error");
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.ToString();
                return View("Error");
            }

            return View();
        }

        // GET: Coupon/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var responseApi = await httpClient.GetAsync($"{urlBase}/coupons/{id}");
                if (responseApi.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    string response = await responseApi.Content.ReadAsStringAsync();
                    var parseResponse = JsonConvert.DeserializeObject<ResponseBase<Coupon>>(response);

                    if (parseResponse.Success && parseResponse.Element != null)
                    {
                        return View(parseResponse.Element);
                    }
                    else
                    {
                        ViewBag.Error = parseResponse.Messaje;
                        return View("Error");
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.ToString();
                return View("Error");
            }

            return View();
        }

        // POST: Coupon/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id, FormCollection collection)
        {
            try
            {
                var responseApi = await httpClient.DeleteAsync($"{urlBase}/coupons/{id}");
                if (responseApi.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    string response = await responseApi.Content.ReadAsStringAsync();
                    var parseResponse = JsonConvert.DeserializeObject<ResponseBase<Coupon>>(response);

                    if (parseResponse.Success)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Error = parseResponse.Messaje;

WebAppKuspyKreme/Views/Coupon/Create.cshtml
@model WebAppKuspyKreme.Models.Coupon

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Coupon</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Serie, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Serie, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Serie, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Establishment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Establishment.Id, (List<SelectListItem>)ViewBag.ListEstablishment, "---")
            @Html.ValidationMessageFor(model => model.Establishment.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Status.Id, (List<SelectListItem>)ViewBag.ListStatus, "---")
            @Html.ValidationMessageFor(model => model.Status.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppKuspyKreme/Views/Coupon/Delete.cshtml
@model WebAppKuspyKreme.Models.Coupon

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Coupon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Serie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebAppKuspyKreme/Views/Coupon/Details.cshtml
@model WebAppKuspyKreme.Models.Coupon

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Coupon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Serie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebAppKuspyKreme/Views/Coupon/Edit.cshtml
@model WebAppKuspyKreme.Models.Coupon

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Coupon</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Serie, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Serie, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Serie, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Establishment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Establishment.Id, (List<SelectListItem>)ViewBag.ListEstablishment, "")
            @Html.ValidationMessageFor(model => model.Establishment.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Status.Id, (List<SelectListItem>)ViewBag.ListStatus, "")
            @Html.ValidationMessageFor(model => model.Status.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppKuspyKreme/Views/Coupon/ExchangeGet.cshtml
@model WebAppKuspyKreme.Models.Coupon

@{
    //ViewBag.Title = "ExchangeGet";
    Layout = null;
}

@*<h2>Exchange Coupon</h2>*@

<div>
    <h4>Exchange Coupon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Serie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletedAt)
        </dd>

    </dl>
</div>
<p>

@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            @Html.ActionLink("Aceptar", "ExchangePut", new { id = Model.Id}, new { @class = "btn btn-primary" })
        </div>
    }
</p>

WebAppKuspyKreme/Views/Coupon/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc;
@model IEnumerable<WebAppKuspyKreme.Models.Coupon>

@{
    ViewBag.Title = "Index";
    var pagedList = (IPagedList)ViewBag.PageList;
}

<h2>Index</h2>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Coupon</h4>
            </div>
            <div class="modal-body">
                <div id="modal-content">loading</div>
            </div>
            @*<div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>*@
        </div>
    </div>
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="form-horizontal">
    <div class="form-inline">

        @*<div class='input-group date' id='datetimepicker10'>
            <input type='text' class="form-control" placeholder="Date Init MM/DD/YYY" />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar">
                </span>
            </span>
        </div>

        <div class='input-group date' id='datetimepicker10'>
            <input type='text' class="form-control" placeholder="Date End MM/DD/YYY" />
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar">
                </span>
            </span>
        </div>*@

        <label>Status</label>
        <select class="form-control">
            <option>DISPONIBLE</option>
            <option>CANJEADO</option>
            <option>VENCIDO</option>
        </select>

        <label>Establisment</label>
        <select class="form-control">
            <option>ESTABLISHMENT 1</option>
            <option>ESTABLISHMENT 2</option>
            <option>ESTABLISHMENT 3</option>
        </select>

        <input class="btn btn-primary" type="button" value="Search" onclick="location.href='@Url.Action("DownloadExcel","Coupon")' " />

        <input class="btn btn-success" type="button" value="Download Excel" onclick="location.href='@Url.Action("DownloadExcel","Coupon")' " />

    </div>
</div>
<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Serie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Establishment)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Serie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Establishment.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |

                @if (item.Status.Id.Equals(1))
                {
                    <a href="#myModal" class="BtnExchange btn btn-primary" data-toggle="modal" data-id="@item.Id"><i class="glyphicon glyphicon-pencil"></i> Exchange</a>
                }
            </td>
        </tr>
    }

</table>

@Html.PagedListPager(pagedList, page =>
    Url.Action("Index", new { page = page }),
    new PagedListRenderOptions
    {
        LiElementClasses = new string[] { "page-item" },
        PageClasses = new string[] { "page-link" }

    })


@section scripts{
    <script src="~/Content/Script/main.js"></script>
}